### PR TITLE
Enables google search console

### PR DESCRIPTION
**Pull request by naps62**

### CODE REVIEW

**Comment by frm** [comment]
Don't you need to include the actual page? Or will this default to the one on the main website since this is mounted at `/blog`?

**Comment by naps62** [comment]
Actually that reminds me, this is not needed. since this will live under `/blog`, google should fetch the one on the base site, which is already hosted by the site itself. Right?

**Comment by frm** [comment]
You are correct. I thought this was the GA PR and you had simply updated it. My bad.

**Comment by frm** [comment]
Can we close this @naps62 ?

**Pull request merged**
